In [1]:
import numpy as np
import xgboost as xb
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, cross_val_score
import warnings
warnings.filterwarnings('ignore')

## Gettting Synthetic data & splitting

In [2]:
make_classification

<function sklearn.datasets._samples_generator.make_classification(n_samples=100, n_features=20, *, n_informative=2, n_redundant=2, n_repeated=0, n_classes=2, n_clusters_per_class=2, weights=None, flip_y=0.01, class_sep=1.0, hypercube=True, shift=0.0, scale=1.0, shuffle=True, random_state=None)>

In [3]:
X, y = make_classification(n_samples = 1000, n_features=20,
                          n_informative = 2,n_redundant=10,random_state = 42
                          )


In [8]:
X

array([[-0.49693203, -0.33912228,  0.22914552, ..., -1.17927302,
         0.45780561,  0.35600629],
       [ 0.01249932,  1.00744397,  0.14009566, ..., -1.76385344,
         0.93791554,  0.45936344],
       [-0.72021202, -1.24448645, -0.47229097, ...,  0.41394755,
        -0.5387903 , -0.26636053],
       ...,
       [ 1.01027459, -0.13092581,  1.18030384, ..., -1.98959095,
        -0.80579965,  0.88702644],
       [-1.20775939, -0.3807634 ,  0.12906749, ..., -0.77725344,
         0.59910333,  0.22671772],
       [ 1.14356604, -0.42459817, -0.31394763, ...,  1.24769039,
        -0.30704834, -0.40246308]])

In [5]:
y

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=42)

## XGBoost Classifier

In [15]:
clf = xb.XGBClassifier(use_label_encoder=False, eval_matric ='logloss')
clf.fit(X_train, y_train)  # train & test data seperated

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_matric='logloss', eval_metric=None,
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [27]:
clf.score(X_test, y_test) # evaluting unseen / testing data

0.9133333333333333

## K-Fold Cross Validation

In [28]:
kf = KFold(n_splits=5, random_state=42, shuffle=True) 
kf_scores = cross_val_score(clf, X,y, cv=kf) # work on full data(X,y),not on train & test. 5 splits that mean each fold contain 20% of data

In [18]:
kf_scores

array([0.915, 0.925, 0.91 , 0.9  , 0.885])

In [29]:
kf_scores.mean()

0.907

## Stratefied K-Fold Cross- validation

- In each data distribution will be same/ equal

In [19]:
skf = KFold(n_splits=5, random_state=42, shuffle=True)
skf_scores = cross_val_score(clf,X, y, cv=skf)

In [26]:
skf_scores

array([0.915, 0.925, 0.91 , 0.9  , 0.885])

In [30]:
skf_scores.mean()

0.907

### Notes

#### Why XGBoost Considered as Ensemble Machine Learning algorithm ?

XGBoost, short for eXtreme Gradient Boosting, is indeed an ensemble machine learning algorithm. Let me explain why:

<b> 1. Ensemble Learning:</b>
Ensemble learning combines the predictions of multiple weak models (also known as base models or learners) to create a stronger model.
The idea is that by combining the outputs of several individual models, we can improve overall prediction accuracy and robustness.

2. Gradient Boosting:
XGBoost is based on the gradient boosting framework.
Gradient boosting is an iterative technique that builds a strong model by sequentially adding weak models to correct the errors made by the previous ones.
It minimizes a loss function by adjusting the weights of individual models during training

3. Decision Trees:
XGBoost uses a decision tree-based approach.
Each tree in XGBoost is trained on a subset of the data and a random selection of features.
Decision trees are simple models that make predictions based on a series of binary decisions (tests on attribute values).

4. Combining Weak Models:
XGBoost combines multiple decision trees (weak models) to create a more powerful ensemble.
Each tree contributes to the final prediction, and their outputs are combined using a weighted sum.

5. Efficiency and Scalability:
XGBoost is designed for efficient and scalable training of machine learning models.
It handles large datasets effectively and achieves state-of-the-art performance.
Built-in support for parallel processing allows training on large datasets within a reasonable time.

6. Handling Missing Values:
XGBoost efficiently handles missing values without requiring extensive pre-processing.
This makes it suitable for real-world data with incomplete information.

7. Customizability:
XGBoost is highly customizable.
You can fine-tune various model parameters to optimize performance for specific tasks.
In summary, XGBoost’s ability to combine weak models, handle missing values, and achieve high performance has made it a popular choice for various machine learning tasks, including classification, regression, and recommendation systems

- Make_classification : its a module for generating dataset, or make_regression
- cross_val_score: for evaluating scores



## Difference between Kfold & Stratified Kfolds

Let’s explore the main differences between KFold and StratifiedKFold:

KFold:
KFold is a cross-validator that divides the dataset into k folds.
It randomly splits the data into training and test sets, ensuring that each fold contains an equal number of samples.
The class distribution is not considered during the split.
It is commonly used for regression tasks or when the class distribution is balanced.

StratifiedKFold:
StratifiedKFold is also a cross-validator, but it returns stratified folds.
It ensures that each fold has the same proportion of observations for each class as the original dataset.
StratifiedKFold is particularly useful for classification tasks with imbalanced class distributions.
It helps maintain the class balance in both training and test sets.

Example:
Suppose we have a dataset with 16 data points: 12 belong to class A, and 4 belong to class B (imbalanced).
If we use StratifiedKFold with k = 4, each fold will have 9 data points from class A and 3 data points from class B in the training set. The test set will have 3 data points from class A and 1 data point from class B.
In contrast, KFold would not consider class proportions and might create imbalanced splits.

When to Use:
KFold: Use KFold when dealing with balanced datasets or regression tasks.
StratifiedKFold: Prefer StratifiedKFold when handling classification tasks with imbalanced class distributions.
In summary, StratifiedKFold is an improved version of KFold that preserves class proportions, making it more suitable for imbalanced datasets