# NumPy

# 4.3. Functions to Create Arrays

In [1]:
# Example of creating an array with the array() function.
# Library
from numpy import array

# Create Array
l = [1.0, 2.0, 3.0]
a = array(l)

# Display Array
print(a)

# Display Array Shape
print(a.shape)

# Display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


### There are more convenience functions for creating fixed-sized arrays

## 4.3.1 Empty

- The empty() function will create a new array of the <b>specified shape</b>.
- The values or content of the created array will be <b>random </b> and will need to be assigned before use
- The example below creates an empty 3 × 3 two-dimensional array.

In [2]:
# Listing 4.3: Example of creating an array with the empty() function.
# Package
from numpy import empty

# Create empty array
a = empty([3,3])
print(a)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [2.33646845e-307 1.42413555e-306 1.78019082e-306]
 [1.37959740e-306 2.29178686e-312 0.00000000e+000]]


# 4.3.2 Zeros

- The zeros() function will create a new array of the <b> specified size </b> with the contents filled with <b> zero values</b>
- The arg to the function is an <b> array or tuple </b> that specifies the length of each dimenstion of the array


In [3]:
# Example of creating an array with the zeros() function.
# Create Zero Arrays
from numpy import zeros

a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 4.3.3 Ones

In [4]:
# Example of creating an array with the ones() function.

# Create One array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


# 4.4 Combining Arrays

- Vertical Stack
- Horizontal Stack

- Vertical Stack: you can stack them vertically using the vstack() function.
- For example, given two one-dimensional arrays, you can create a new two-dimensional array with two rows by vertically stacking them.

- Horizontal Stack: you can stack them horizontally using the hstack() function
-  given two one-dimensional arrays, you can create a new one-dimensional array or one row with the columns of the first and second arrays concatenated

## 4.4.1 Vertical Stack

#### Example of creating an array from other arrays using the vstack() function.

In [5]:
#  create array with vstack
from numpy import array
from numpy import vstack

# Create first array
a1 = array([1,2,3])
print(a1)

# Create second Array
a2 = array([4,5,6])
print(a2)

[1 2 3]
[4 5 6]


In [6]:
# Vertical Stack
a3 = vstack((a1, a2))
print(a3)

[[1 2 3]
 [4 5 6]]


In [7]:
# Shape
print(a3.shape)

(2, 3)


## 4.4.2 Horizontal Stack

#### Example of creating an array from other arrays using the hstack() function

In [8]:
# Create array with hstack
from numpy import array
from numpy import hstack

# create first array
a1 = array([1,2,3])
print(a1)

# create second array
a2 = array([4,5,6])
print(a2)


[1 2 3]
[4 5 6]


In [9]:
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)

[1 2 3 4 5 6]


In [10]:
# Display Shape
print(a3.shape)

(6,)


### Summary

- array()
- empty()
- zeros()
- ones()
- vstack()
- hstack()

# Chapter 5

#### Index, Slice & Reshape NumPy Arrays

### 5.1 Overview

- From List to Arrays
- Array Indexcing
- Array Slicing
- Array Reshaping

## 5.2 From List to Arrays

#### 5.2.1 One - Dimensional List to Array

In [11]:
## example converts the one-dimensional list to a NumPy array
# create one-dimensional array
from numpy import array

# list of data
data = [11, 22, 33, 44, 55]

# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


#### 5.2.2 Two - Dimensional List to Array

In [12]:
# Example of creating two-dimensional array
# create two-dimensional array
from numpy import array

# list of data
data = [[11, 22],
       [33, 44],
       [55, 66]]

# array of data
data = array (data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


## 5.3 Array Indexing

- Once your data is represented using a NumPy array, you can <b>EASILY ACCESS</b> it using indexing.

### 5.3.1 One - Dimentional Indexcing

In [13]:
# Example of indexing a one-dimensional array
# Index a one-dimensional array
from numpy import array

# define array
data = array([11, 22, 33, 44, 55])

# index data
print(data[0]) # first index e.g 11
print(data[4]) # Lst index
print(data[-1])
print(data[-2])

11
55
55
44


In [14]:
# Example of an error when indexing a one-dimensional array.
from numpy import array


# define array
# data = array([11, 22, 33, 44, 55])
# # index data
# print(data[5])

# IndexError: index 5 is out of bounds for axis 0 with size 5

In [15]:
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])

55
11


### 5.3.2 Two - Dimentional Indexcing

- Indexing two-dimensional data is similar to indexing one-dimensional data, except that a <b> comma is used to separate the index </b> for each dimension.


In [16]:
# Example of indexing a two-dimensional array.
# index two-dimentional array
from numpy import array

# define array
data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])

# index data
print(data[0,0]) # 1st row: 1st col (1st index)
print(data[0,1]) # 1st row: 2nd col (1st index); can not call by index 2 (index error: out of bound)
print(data[1,0]) # 2nd row: 1st col (e.g 33)
print(data[1,1]) # 2nd row: 2nd col (e.g 44)
print(data[2,0]) # 3rd row: 1st col (e.g 55)
print(data[2,1]) # 3rd row: 2nd col (e.g 66)

11
22
33
44
55
66


In [17]:
# all items in the first row, we could leave the second dimension index empty

from numpy import array
# define array
data = array([
    [11, 22],
    [33, 44],
    [55, 66]
])

# index data

print(data[0,]) # all items in 1st row
print(data[1,]) # all items in 2nd row
print(data[2,]) # all items in 3rd row


[11 22]
[33 44]
[55 66]


In [18]:
print(data[:]) # All rows: all cols

[[11 22]
 [33 44]
 [55 66]]


## 5.4 Array Slicing

-  Structures like lists and NumPy arrays can be sliced
- This means that a subsequence of the structure can be indexed and retrieved
- This is most useful in machine learning when specifying input variables and output variables, or splitting training rows from testing rows
- Slicing is specified using the colon operator : with a from and to index before and after the column respectively.
- The slice extends from the from index and ends one item before the to index.

- Syntax:  data[from:to]



### 5.4.1 One - Dimentional Slicing


- You can access all data in an array dimension by specifying the slice ‘:’ with no indexes.

In [19]:
# Example of slicing a one-dimensional array
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


- The first item of the array can be sliced by specifying a slice that starts at index 0 and ends at index 1 (one item before the to index)

In [20]:
# slice a subset of a one-dimensional array
from numpy import array

# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])
print(data[:1])
print(data[0:2])
print(data[0:3])
print(data[1:2])
print(data[2:4])
print(data[2:5]) # excludes last one
print(data[2:7]) # For any upper value, it will show upto last index e.g 55
print(data[3:4])
print(data[3:5])
print(data[3:6])

[11]
[11]
[11 22]
[11 22 33]
[22]
[33 44]
[33 44 55]
[33 44 55]
[44]
[44 55]
[44 55]


- 28

## 5.4.3 Two - Dimentional Slicing

### Split Input and Output Features

- It is common to split your loaded data into input variables (X) and the output variable (y).
- We can do this by slicing all rows and all columns up to, but before the last column, then separately indexing the last column
- For the input features, we can select all rows and all columns except the last one by specifying : for in the rows index, and :-1 in the columns index.

-  X = [:, :-1]          Example of slicing input variables.
- y = [:, -1]            Example of slicing the output variable

In [22]:
# Putting all of this together, we can separate a 3-column 2D dataset into input and output data as follows:

# Split Input & Output Data
from numpy import array

# define data
data = array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])

# seperate data
X, y = data[:, :-1], data[:, :-1]

print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[[11 22]
 [44 55]
 [77 88]]
